export const phrases = [
  "Winding up the gramophone...",
  "Perusing the pages of the NME...",
  "Dusting off the vinyl...",
  "Tuning the theremin...",
  "Polishing the brass section...",
  "Calling the roadies...",
  "Checking the guest list...",
  "Finding the perfect band name...",
  "Arguing about the setlist...",
  "Designing the album art...",
  "Soundchecking the Moog...",
  "Calibrating the vocoder...",
  "Locating the lost plectrum...",
  "Untangling the patch cords...",
  "Updating the band's MySpace page...",
  "Teaching the drummer to count to 4...",
  "Hunting for a cowbell...",
  "Debating the merits of prog rock...",
  "Googling 'what is a keytar?'...",
  "Re-stringing the sitar...",
  "Asking the producer for a bigger budget...",
  "Trying to get a decent snare sound...",
  "Warming up the bagpipes...",
  "Looking for a rhyme for 'orange'...",
  "Applying the eyeliner...",
  "Negotiating the rider...",
  "Stenciling the flight cases...",
  "Building a wall of amps...",
  "Stretching the leather trousers...",
  "Finding a bassist who can also sing...",
  "Harmonizing with the theremin...",
  "Writing a song about a hobbit...",
  "Perfecting the power stance...",
  "Learning the lyrics...",
  "Avoiding the brown acid...",
  "Choosing the font for the album cover...",
  "Arguing with the label A&R...",
  "Reticulating splines...",
  "Adding more echo...",
  "Mastering the key change...",
  "Waiting for the singer to show up...",
  "Loading the tour bus...",
  "Polishing the gold records...",
  "Signing the record deal...",
  "Herding the rockstars...",
  "Assembling the drum kit...",
  "Plugging in the wah-wah pedal...",
  "Ironing the stage outfits...",
  "Teasing the hair...",
  "Hiring a smoke machine...",
  "Finding a groupie to translate the lyrics...",
  "Checking the pyrotechnics...",
  "Rolling out the red carpet...",
  "Inscribing the rock and roll hall of fame...",
  "Adding more cowbell...",
];
